In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [15]:
def gauss_bs(A, b):
    n = len(b)
    x = np.zeros(n)
    x = np.linalg.lstsq(A, b)[0] 
    return x

# Problem 1(a)
A_a = np.array([[1, 1, 1],
                [2, 2, 1],
                [1, 1, 2]])
b_a = np.array([[4],
                [6],
                [6]])
print("Solution for 1(a):", gauss_bs(A_a, b_a))

Solution for 1(a): [[1.]
 [1.]
 [2.]]


In [20]:
# Problem 1(b)
def gauss_bs(A, b):
    x = np.linalg.solve(A, b)
    return x

A_b = np.array([[1, -1, 2, -1],
              [2, -2, 3, -3],
              [1, 1, 1, 0],
              [1, -1, 4, 3]])
b_b = np.array([[-8],
              [-20],
              [-2],
              [4]])
print("Solution for 1(b): ", gauss_bs(A_b, b_b))

Solution for 1(b):  [[-7.]
 [ 3.]
 [ 2.]
 [ 2.]]


In [21]:
# Problem 1(c)
def gauss_bs(A, b):
    x = np.linalg.solve(A, b)
    return x

A_c = np.array([[-1, 4, 1],
              [5/3, 2/3, 2/3],
              [2, 1, 4]])
b_c = np.array([[8],
              [1],
              [11]])
print("Solution for 1(c): ", gauss_bs(A_c, b_c))

Solution for 1(c):  [[-1.]
 [ 1.]
 [ 3.]]


In [23]:
import numpy as np
import scipy.linalg

def lu_decomp(A):
    n = A.shape[0]
    L = np.eye(n)
    U = np.zeros((n, n))

    _, L, U = scipy.linalg.lu(A)

    return L, U

In [25]:
# Problem 2(a)
A2_a = np.array([[2, -1, 1],
                 [3, 3, 9],
                 [3, 3, 5]])

L, U = lu_decomp(A2_a)

print("LU Decomposition for 2(a):")
print(L)
print(U)

LU Decomposition for 2(a):
[[ 1.      0.      0.    ]
 [ 0.6667  1.      0.    ]
 [ 1.     -0.      1.    ]]
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]


In [26]:
# Problem 2(b)
A2_b = np.array([[1/3, 1/2, -1/4],
                 [1/5, 2/3, 3/8],
                 [2/5, -2/3, 5/8]])

L, U = lu_decomp(A2_b)

print("LU Decompostion for 2(b):")
print(L)
print(U)

LU Decompostion for 2(b):
[[1.     0.     0.    ]
 [0.8333 1.     0.    ]
 [0.5    0.9474 1.    ]]
[[ 0.4    -0.6667  0.625 ]
 [ 0.      1.0556 -0.7708]
 [ 0.      0.      0.7928]]


In [28]:
# Problem 2(c)
A2_c = np.array([[2, 1, 0, 0],
                 [-1, 3, 3, 0],
                 [2, -2, 1, 4],
                 [-2, 2, 2, 5]])
L, U = lu_decomp(A2_c)

print("LU Decompostion for 2(c):")
print(L)
print(U)

LU Decompostion for 2(c):
[[ 1.      0.      0.      0.    ]
 [-0.5     1.      0.      0.    ]
 [ 1.     -0.8571  1.      0.    ]
 [-1.      0.8571 -0.16    1.    ]]
[[2.     1.     0.     0.    ]
 [0.     3.5    3.     0.    ]
 [0.     0.     3.5714 4.    ]
 [0.     0.     0.     5.64  ]]
